// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import "github.com/jackc/pgx/v5/pgtype"

type User struct {
	ID        int32
	Email     string
	FirstName pgtype.Text
	LastName  pgtype.Text
	Password  string
	Active    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
