// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

// DeleteUser
//
//	DELETE FROM users WHERE id = $1
func (q Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, email, first_name, last_name, password, active, created_at, updated_at FROM users 
ORDER BY last_name
`

// GetAll
//
//	SELECT id, email, first_name, last_name, password, active, created_at, updated_at FROM users
//	ORDER BY last_name
func (q Queries) GetAll(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Password,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByEmail = `-- name: GetByEmail :one
SELECT id, email, first_name, last_name, password, active, created_at, updated_at FROM users WHERE email = $1
`

// GetByEmail
//
//	SELECT id, email, first_name, last_name, password, active, created_at, updated_at FROM users WHERE email = $1
func (q Queries) GetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Password,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByID = `-- name: GetByID :one
SELECT id, email, first_name, last_name, password, active, created_at, updated_at FROM users WHERE id = $1
`

// GetByID
//
//	SELECT id, email, first_name, last_name, password, active, created_at, updated_at FROM users WHERE id = $1
func (q Queries) GetByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Password,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users 
        (email, first_name, last_name, password, active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7) 
RETURNING id, email, first_name, last_name, password, active, created_at, updated_at
`

type InsertUserParams struct {
	Email     string
	FirstName pgtype.Text
	LastName  pgtype.Text
	Password  string
	Active    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// InsertUser
//
//	INSERT INTO users
//	        (email, first_name, last_name, password, active, created_at, updated_at)
//	VALUES ($1, $2, $3, $4, $5, $6, $7)
//	RETURNING id, email, first_name, last_name, password, active, created_at, updated_at
func (q Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Password,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Password,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users 
SET password = $1 
WHERE id = $2
`

type UpdatePasswordParams struct {
	Password string
	ID       int32
}

// UpdatePassword
//
//	UPDATE users
//	SET password = $1
//	WHERE id = $2
func (q Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.Password, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
email = $1,
first_name = $2,
last_name = $3,
active = $4,
updated_at = $5
WHERE id = $6
RETURNING id, email, first_name, last_name, password, active, created_at, updated_at
`

type UpdateUserParams struct {
	Email     string
	FirstName pgtype.Text
	LastName  pgtype.Text
	Active    int32
	UpdatedAt pgtype.Timestamptz
	ID        int32
}

// UpdateUser
//
//	UPDATE users SET
//	email = $1,
//	first_name = $2,
//	last_name = $3,
//	active = $4,
//	updated_at = $5
//	WHERE id = $6
//	RETURNING id, email, first_name, last_name, password, active, created_at, updated_at
func (q Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Active,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Password,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
