services:

  broker-service:
    build:
      dockerfile: ./broker/broker.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  logger-service:
    build:
      dockerfile: ./logger/logger.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DB_URI: mongodb://mongodb:27017
      DB_USER: ${MONGO_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mongodb

  authentication-service:
    build:
      dockerfile: ./authentication/authentication.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres

  mail-service:
    build:
      dockerfile: ./mail/mail.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

  postgres:
    image: 'postgres:18.3'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql

  mongodb:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: logs
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: